<a href="https://colab.research.google.com/github/qinhuuuuu/MachineLearning/blob/main/Lab1_20130356_PhanThiQuynhNhu.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# 1.1
n = int(input("n: "))
list = []
for i in range(n):
    list.append(int(input("x: ")))
print(list)

print("Max: ",max(list))
print("Min: ",min(list))
print("Sum: ",sum(list))
print("List sorted: ",sorted(list))

n: 5
x: 123
x: -23
x: 443
x: 2
x: 0
[123, -23, 443, 2, 0]
Max:  443
Min:  -23
Sum:  545
List sorted:  [-23, 0, 2, 123, 443]


In [2]:
# 1.2
def Sn(n):
  S = 0
  for i in range(n+1):
    S += 1/(2*i+1)
  return S
print(Sn(int(input("n: "))))

def SnDQ(n):
  if n == 0:
    return 1
  else:
    return SnDQ(n-1) + 1/(2*(n)+1)
print(SnDQ(int(input("n: "))))

n: 3
1.676190476190476
n: 3
1.676190476190476


In [10]:
from abc import ABC, abstractmethod
from datetime import date

class Order:
    def __init__(self, ids, customer, employee, date, items):
        self.__ids = ids
        self.__customer = customer
        self.__employee = employee
        self.__date = date
        self.__items = items

    @property
    def ids(self):
        return self.__ids

    @ids.setter
    def ids(self, value):
        self.__ids = value

    @property
    def customer(self):
        return self.__customer

    @customer.setter
    def customer(self, value):
        self.__customer = value

    @property
    def employee(self):
        return self.__employee

    @employee.setter
    def employee(self, value):
        self.__employee = value

    @property
    def date(self):
        return self.__date

    @date.setter
    def date(self, value):
        self.__date = value

    @property
    def items(self):
        return self.__items

    @items.setter
    def items(self, value):
        self.__items = value

    def __repr__(self):
        return str(self.__ids) + " " + self.__customer

    def getListProductInOrder(self):
        result = []
        for item in self.__items:
            result.append(item.item)
        return result

    def getProductHighestPriceInOder(self):
        return max(self.getListProductInOrder(), key=lambda item: item.price)

    def showNumberOfProducts(self):
        counts = dict()
        for oderItem in self.__items:
            counts[oderItem.item] = counts.get(oderItem.item, 0) + oderItem.amount
        return counts


class OrderItem:
    def __init__(self, item, amount):
        self.__item = item
        self.__amount = amount

    @property
    def item(self):
        return self.__item

    @item.setter
    def item(self, value):
        self.__item = value

    @property
    def amount(self):
        return self.__amount

    @amount.setter
    def amount(self, value):
        self.__amount = value

    def __repr__(self):
        return str(self.__item) + " " + str(self.__amount)


class OrderManager:
    def __init__(self, orders):
        self.__orders = orders

    @property
    def orders(self):
        return self.__orders

    @orders.setter
    def orders(self, value):
        self.__orders = value

    def __repr__(self):
        return self.__orders

    def getListProductHighestPriceInAOder(self):
        result = []
        for item in self.__orders:
            result.append(item.getProductHighestPriceInOder())
        return result

    def getProductHighestPriceInOders(self):
        return max(self.getListProductHighestPriceInAOder(), key=lambda item: item.price)

    def showNumberOfProducts(self):
        counts = dict()
        for oder in self.__orders:
            for product, amount in oder.showNumberOfProducts().items():
                counts[product] = counts.get(product, 0) + amount
        return counts


class Product(ABC):
    def __init__(self, name, kind, price, expiredDate):
        self._name = name
        self._kind = kind
        self._price = price
        self._expiredDate = expiredDate

    @property
    def name(self):
        return self._name

    @name.setter
    def name(self, value):
        self._name = value

    @property
    def kind(self):
        return self._kind

    @kind.setter
    def kind(self, value):
        self._kind = value

    @property
    def price(self):
        return self._price

    @price.setter
    def price(self, value):
        self._price = value

    @property
    def expiredDate(self):
        return self._expiredDate

    @expiredDate.setter
    def expiredDate(self, value):
        self._expiredDate = value

    def __repr__(self):
        return self.name + " " + str(self._price)


class ImportedProduct(Product):
    def __init__(self, name, kind, price, expiredDate, fromCountry):
        super().__init__(name, kind, price, expiredDate)
        self.__fromCountry = fromCountry

    @property
    def fromCountry(self):
        return self.__fromCountry

    @fromCountry.setter
    def fromCountry(self, value):
        self.__fromCountry = value

    def __repr__(self):
        return self.name + " " + str(self._price) + ' ' + self.fromCountry


class DomesticProduct(Product):
    def __init__(self, name, kind, price, expiredDate):
        super().__init__(name, kind, price, expiredDate)


d = date(2002, 12, 31)
p1 = ImportedProduct("tra sua", "tra trai cay", 20500, d, 'trung quoc')
p2 = DomesticProduct("tra vai", "tra trai cay", 30000, d)
p3 = ImportedProduct("tra dao", "tra trai cay", 40000, d, 'han quoc')
p4 = DomesticProduct("tra o long", "tra trai cay", 50000, d)
od_item1 = OrderItem(p1, 2)
od_item2 = OrderItem(p2, 5)
od_item3 = OrderItem(p3, 1)
od_item4 = OrderItem(p4, 7)
od_item5 = OrderItem(p1, 3)
od_item6 = OrderItem(p3, 1)
od_item7 = OrderItem(p2, 2)
o1 = Order(1, 'nhuw', 'quynh', date, [od_item3, od_item5, od_item6])
o2 = Order(2, 'nhuw', 'quynh', date, [od_item1, od_item2])
o3 = Order(3, 'nhuw', 'quynh', date, [od_item1, od_item5, od_item7])
om1 = OrderManager([o1, o2, o3])

print('San pham gia cao nhat la ', om1.getProductHighestPriceInOders())
print('So san pham theo loai la ', om1.showNumberOfProducts())

San pham gia cao nhat la  tra dao 40000 han quoc
So san pham theo loai la  {tra dao 40000 han quoc: 2, tra sua 20500 trung quoc: 10, tra vai 30000: 7}


In [4]:
# 2.1
import numpy as np
array = np.arange(10, 26, 1)
array = array[::-1]
print(array)

[25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


In [6]:
# 2.2
x = int(input("x: "))
array = np.arange(1, 5, 1)
print(np.tile(array, x))

x: 3
[1 2 3 4 1 2 3 4 1 2 3 4]


In [8]:
# 2.3
x = np.array([[0.42, 0.48, 0.32], [0.74, 0.58, 0.38], [0.5, 0.34, 0.15]])
x[x > 0.5] = 0.5
print(x)

[[0.42 0.48 0.32]
 [0.5  0.5  0.38]
 [0.5  0.34 0.15]]
